name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # ------------------------------
      # Maven Build / Tests / Analysis
      # ------------------------------
      - name: Run unit tests (Maven Surefire)
        run: mvn -B test 2>&1 | tee -a build.log

      - name: Run integration tests (Maven Failsafe / verify)
        run: mvn -B verify 2>&1 | tee -a build.log

      - name: Static analysis — Checkstyle
        run: mvn -B org.apache.maven.plugins:maven-checkstyle-plugin:3.3.1:check 2>&1 | tee -a build.log || true

      - name: Static analysis — SpotBugs
        run: mvn -B com.github.spotbugs:spotbugs-maven-plugin:4.8.3.1:check 2>&1 | tee -a build.log || true

      # ------------------------------
      # Upload Artifacts
      # ------------------------------
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**

      - name: Archive Maven logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: maven-logs
          path: build.log
